import { CATEGORIES, SIGNALS } from "@/lib/reasoning-engine/constants";
import {
    describeRentalProblem,
    evaluateVehicle,
    formatEUR,
    periodLabel,
    priorityWeights,
    rentalPeriodOf,
} from "@/lib/reasoning-engine";
import { totalFor } from "@/lib/reasoning-engine/scoring";
import type { Recommendation } from "@/lib/reasoning-engine/types";
import { configurationName } from "@/lib/car-labels";
import type { PinnedFinnCar } from "@/lib/types";

import type { Answers } from "@/entrypoints/compare/store";

/**
 * "Here's what changed", written from two runs of the real engine.
 *
 * Nothing here is generated by a model. A what-if is only honest if the
 * answer to it comes from the same arithmetic as the recommendation it is
 * being compared with, so both sides of this are `Recommendation`s built by
 * `buildRecommendation`, and every sentence below quotes their fields.
 */

export interface OutcomeCar {
    id: number;
    name: string;
    image: string | null;
    total: number;
    monthly: number;
    isFallback: boolean;
}

export interface Outcome {
    winnerChanged: boolean;
    before: OutcomeCar;
    after: OutcomeCar;
    headline: string;
    /** The largest movement in the answers, said once. */
    cause: string | null;
    /** What the engine's numbers say about the result, most telling first. */
    details: string[];
}

/** A car's name, with its configuration where two pinned cars share one. */
export function carLabel(car: PinnedFinnCar, cars: PinnedFinnCar[]): string {
    const shared = cars.some((other) => other.id !== car.id && other.name === car.name);

    return shared ? `${car.name} ${configurationName(car)}` : car.name;
}

function outcomeCar(rec: Recommendation, cars: PinnedFinnCar[]): OutcomeCar {
    const { winner, context } = rec;

    return {
        id: winner.id,
        name: carLabel(winner, cars),
        image: winner.images?.thumbnail || null,
        total: totalFor(context.scores, winner.id),
        monthly: context.costs[winner.id]?.totalMonthly ?? 0,
        isFallback: rec.isFallback,
    };
}

/** The single biggest thing that moved in the answers, as a sentence. */
function describeCause(before: Answers, after: Answers): string | null {
    const was = priorityWeights(before.priorities);
    const now = priorityWeights(after.priorities);

    const moves = now
        .map((weight) => {
            const previous = was.find((item) => item.priority === weight.priority);

            return { weight, previous, delta: previous ? previous.rank - weight.rank : Infinity };
        })
        .filter((move) => move.delta !== 0);

    const label = (id: keyof typeof CATEGORIES) => CATEGORIES[id].label;

    const joined = moves.find((move) => move.previous == null);

    if (joined) {
        return `${label(joined.weight.priority)} joining your priorities at #${joined.weight.rank}, where it carries ${joined.weight.weightPercent}% of the result.`;
    }

    const biggest = [...moves].sort(
        (a, b) => Math.abs(b.delta) - Math.abs(a.delta),
    )[0];

    if (biggest?.previous) {
        return `${label(biggest.weight.priority)} moving from #${biggest.previous.rank} to #${biggest.weight.rank}, so it now carries ${biggest.weight.weightPercent}% of the result instead of ${biggest.previous.weightPercent}%.`;
    }

    const dropped = was.find((item) => !after.priorities.includes(item.priority));

    if (dropped) {
        return `${label(dropped.priority)} no longer being one of your priorities.`;
    }

    const budgetBefore = before.preferences.monthlyBudget;
    const budgetAfter = after.preferences.monthlyBudget;

    if (budgetBefore !== budgetAfter) {
        return budgetAfter > 0
            ? budgetBefore > 0
                ? `your budget moving from ${formatEUR(budgetBefore)} to ${formatEUR(budgetAfter)} a month.`
                : `a budget of ${formatEUR(budgetAfter)} a month, where there was no limit.`
            : `removing your ${formatEUR(budgetBefore)} budget.`;
    }

    for (const [category, selection] of Object.entries(after.features)) {
        for (const item of selection) {
            const previous = before.features[category as keyof typeof CATEGORIES]?.find(
                (other) => other.key === item.key,
            );

            if (previous?.importance !== item.importance) {
                return `raising ${SIGNALS[item.key].label} to ${item.importance === "high" ? "Highly" : item.importance === "medium" ? "Moderately" : "Somewhat"} under ${CATEGORIES[category as keyof typeof CATEGORIES].label}.`;
            }
        }
    }

    const periodBefore = rentalPeriodOf(before.preferences);
    const periodAfter = rentalPeriodOf(after.preferences);

    if (JSON.stringify(periodBefore) !== JSON.stringify(periodAfter)) {
        return periodAfter
            ? `renting from ${periodLabel(periodAfter)}${periodBefore ? ` instead of ${periodLabel(periodBefore)}` : ""}, which decides the FINN term each car is priced on and whether it can be delivered in time.`
            : `removing your ${periodLabel(periodBefore!)} rental period.`;
    }

    if (before.preferences.monthlyKm !== after.preferences.monthlyKm) {
        return `your mileage moving from ${before.preferences.monthlyKm} to ${after.preferences.monthlyKm} km a month.`;
    }

    if (before.preferences.contractType !== after.preferences.contractType) {
        return `switching to a ${after.preferences.contractType} contract.`;
    }

    return null;
}

export function compareOutcomes({
    cars,
    before,
    after,
    beforeAnswers,
    afterAnswers,
}: {
    cars: PinnedFinnCar[];
    before: Recommendation;
    after: Recommendation;
    beforeAnswers: Answers;
    afterAnswers: Answers;
}): Outcome {
    const was = outcomeCar(before, cars);
    const now = outcomeCar(after, cars);
    const winnerChanged = was.id !== now.id;

    const causeText = describeCause(beforeAnswers, afterAnswers);
    const details: string[] = [];

    if (winnerChanged) {
        const oldWinner = after.context.vehicles.find((car) => car.id === was.id);

        if (oldWinner) {
            const evaluation = evaluateVehicle(after.winner, after.context, {
                recommendedId: after.winner.id,
                compareWith: oldWinner,
                peers: [after.winner, oldWinner, ...after.alternatives],
            });

            const edge = evaluation.comparison?.decidingAdvantage;

            if (edge?.versus) {
                details.push(
                    `Under these answers ${now.name} is furthest ahead of ${was.name} on ${edge.label} (your #${edge.rank}): ${edge.score} against ${edge.versus.score}.`,
                );
            }

            const oldTotal = totalFor(after.context.scores, oldWinner.id);
            const oldRank = after.ranked.findIndex((car) => car.id === oldWinner.id) + 1;

            details.push(
                `Overall match: ${now.name} ${now.total}, ${was.name} ${oldTotal} — ${was.name} is now #${oldRank} of ${after.ranked.length}.`,
            );

            const oldCost = after.context.costs[oldWinner.id];
            const rentalProblem = oldCost ? describeRentalProblem(oldCost.contract) : null;

            if (rentalProblem) {
                details.push(`${was.name} ${rentalProblem}.`);
            } else if (after.budgetChangedTheAnswer && oldCost?.budgetStatus !== "within" && oldCost?.budget != null) {
                details.push(
                    oldCost.budgetStatus === "over"
                        ? `${was.name} is estimated at ${formatEUR(oldCost.totalMonthly)} a month, ${formatEUR(oldCost.budgetDifference ?? 0)} over your budget, so it can't win.`
                        : `Lens can't confirm ${was.name} fits your budget, so it can't win ahead of a car that does.`,
                );
            }

            const difference = now.monthly - was.monthly;

            if (Math.abs(difference) >= 1) {
                details.push(
                    `${now.name} is estimated at ${formatEUR(now.monthly)} a month — ${formatEUR(Math.abs(difference))} ${difference > 0 ? "more" : "less"} than ${was.name}.`,
                );
            }
        }
    } else {
        const runnerBefore = before.runnerUp;
        const runnerAfter = after.runnerUp;

        if (runnerAfter) {
            const leadNow = now.total - totalFor(after.context.scores, runnerAfter.id);
            const runnerName = carLabel(runnerAfter, cars);

            const leadBefore =
                runnerBefore != null
                    ? was.total - totalFor(before.context.scores, runnerBefore.id)
                    : null;

            details.push(
                leadBefore != null && runnerBefore?.id === runnerAfter.id
                    ? `Its lead over ${runnerName} went from ${leadBefore} to ${leadNow} points (${was.total} → ${now.total} overall).`
                    : `It leads ${runnerName}, now the closest car it's checked against, by ${leadNow} points.`,
            );
        }

        if (now.total !== was.total && !runnerAfter) {
            details.push(`Its overall match went from ${was.total} to ${now.total}.`);
        }
    }

    const budgetBefore = beforeAnswers.preferences.monthlyBudget;
    const budgetAfter = afterAnswers.preferences.monthlyBudget;

    if (budgetBefore !== budgetAfter && budgetAfter > 0) {
        const fits = after.budget.within.length;
        const fitted = before.budget.budget != null ? before.budget.within.length : null;

        details.push(
            `${fits} of ${after.ranked.length} cars are confirmed to fit ${formatEUR(budgetAfter)} a month${fitted != null ? `, against ${fitted} before` : ""}.`,
        );
    }

    if (after.gearboxFallback === "noneFit" && before.gearboxFallback !== "noneFit") {
        details.push("None of your pinned cars is an automatic, so this is the closest match rather than one you can drive.");
    }

    if (after.rentalFallback === "noneFit" && before.rentalFallback !== "noneFit") {
        details.push("None of your pinned cars fits that rental period, so this is the closest match rather than one you can rent for those months.");
    }

    const term = after.context.costs[now.id]?.contract;

    if (term?.period && term.term) {
        details.push(
            `${now.name} is priced on its ${term.term.months}-month FINN term${term.extraMonths ? `, ${term.extraMonths} month${term.extraMonths === 1 ? "" : "s"} longer than you need` : ""}.`,
        );
    }

    if (after.isFallback && !before.isFallback) {
        details.push("Nothing you pinned is confirmed to fit that budget, so this is the closest match rather than an affordable one.");
    }

    return {
        winnerChanged,
        before: was,
        after: now,
        headline: winnerChanged
            ? `Your recommendation changed from ${was.name} to ${now.name}.`
            : `${now.name} is still your recommendation.`,
        cause: causeText
            ? `The biggest difference was ${causeText}`
            : null,
        details,
    };
}
